name: workspace
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  ios: true
  min_sdk_android: 24
  remove_alpha_ios: true
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/image/
    - assets/language/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope-ExtraLight.ttf
          weight: 300
        - asset: assets/font/Manrope-Light.ttf
          weight: 400
        - asset: assets/font/Manrope-Regular.ttf
          weight: 500
        - asset: assets/font/Manrope-Medium.ttf
          weight: 600
        - asset: assets/font/Manrope-SemiBold.ttf
          weight: 700
        - asset: assets/font/Manrope-Bold.ttf
          weight: 800
        - asset: assets/font/Manrope-ExtraBold.ttf
          weight: 900
