name: workspace
description: 'Thesis Project'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  http: ^1.5.0
  url_launcher: ^6.3.2
  connectivity_plus: ^7.0.0
  bloc: ^9.1.0
  fpdart: ^1.1.1
  get_it: ^8.2.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  logger: ^2.6.2
  easy_localization: ^3.0.8
  location: ^8.0.1
  geocoding: ^4.0.0
  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.1
  intl_phone_field: ^3.2.0
  another_flushbar: ^1.12.32
  cached_network_image: ^3.4.1
  infinite_scroll_pagination: ^4.1.0
  pinput: ^5.0.1
  shimmer: ^3.0.0
  dotted_line: ^3.2.3
  dotted_border: ^3.1.0
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  flutter_widget_from_html: ^0.17.1
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.1
  syncfusion_flutter_datepicker: ^31.1.22
  action_slider: ^0.7.0
  permission_handler: ^12.0.1
  fl_chart: ^1.1.1
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  ios: true
  min_sdk_android: 24
  remove_alpha_ios: true
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/image/
    - assets/language/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope-ExtraLight.ttf
          weight: 300
        - asset: assets/font/Manrope-Light.ttf
          weight: 400
        - asset: assets/font/Manrope-Regular.ttf
          weight: 500
        - asset: assets/font/Manrope-Medium.ttf
          weight: 600
        - asset: assets/font/Manrope-SemiBold.ttf
          weight: 700
        - asset: assets/font/Manrope-Bold.ttf
          weight: 800
        - asset: assets/font/Manrope-ExtraBold.ttf
          weight: 900
