name: workspace
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  #NETWORK
  http: ^1.3.0
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.2

  #STATEMANAGEMENT
  bloc: ^9.0.0
  meta: ^1.15.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0

  #UTILS
  intl: ^0.19.0
  logger: ^2.5.0
  upgrader: ^11.3.1
  path_provider: ^2.1.5
  easy_localization: ^3.0.7+1
  permission_handler: ^11.3.1

  #LOCATION
  location: ^8.0.0
  geocoding: ^3.0.0

  #PICKER
  open_file: ^3.5.10
  file_picker: ^8.3.1
  image_picker: ^1.1.2
  month_picker_dialog: ^6.0.3

  #DATABASE
  shared_preferences: ^2.5.1

  #WIDGETS
  flutter_svg: ^2.0.17
  intl_phone_field: ^3.2.0
  another_flushbar: ^1.12.30
  cached_network_image: ^3.4.1
  infinite_scroll_pagination: ^4.1.0

  #UI&DESIGN
  pinput: ^5.0.1
  shimmer: ^3.0.0
  dotted_line: ^3.2.3
  dotted_border: ^2.1.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  gradient_borders: ^1.0.1
  simple_gradient_text: ^1.3.0
  font_awesome_flutter: ^10.8.0

  #ANIMATION
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  ios: true
  min_sdk_android: 24
  remove_alpha_ios: true
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/image/
    - assets/language/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope-ExtraLight.ttf
          weight: 300
        - asset: assets/font/Manrope-Light.ttf
          weight: 400
        - asset: assets/font/Manrope-Regular.ttf
          weight: 500
        - asset: assets/font/Manrope-Medium.ttf
          weight: 600
        - asset: assets/font/Manrope-SemiBold.ttf
          weight: 700
        - asset: assets/font/Manrope-Bold.ttf
          weight: 800
        - asset: assets/font/Manrope-ExtraBold.ttf
          weight: 900
