// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkU13gsTmPngZTC25Bjv8BLTsPhYaptoU',
    appId: '1:444047505948:web:2c5d3ab0206ed84d8abdd9',
    messagingSenderId: '444047505948',
    projectId: 'workspace-292e5',
    authDomain: 'workspace-292e5.firebaseapp.com',
    storageBucket: 'workspace-292e5.firebasestorage.app',
    measurementId: 'G-3R7YB6VNHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWyp8CIWb9EcHZ5i_Ppoxe1Do0N6MJX7o',
    appId: '1:444047505948:android:d57306a70558e3a58abdd9',
    messagingSenderId: '444047505948',
    projectId: 'workspace-292e5',
    storageBucket: 'workspace-292e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2fI-5dEDOvMloai88pHwXAKBWVJubSJc',
    appId: '1:444047505948:ios:f1399bc503812f4c8abdd9',
    messagingSenderId: '444047505948',
    projectId: 'workspace-292e5',
    storageBucket: 'workspace-292e5.firebasestorage.app',
    iosBundleId: 'com.workspace.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2fI-5dEDOvMloai88pHwXAKBWVJubSJc',
    appId: '1:444047505948:ios:4a44b7764e8a4d2a8abdd9',
    messagingSenderId: '444047505948',
    projectId: 'workspace-292e5',
    storageBucket: 'workspace-292e5.firebasestorage.app',
    iosBundleId: 'com.example.workspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkU13gsTmPngZTC25Bjv8BLTsPhYaptoU',
    appId: '1:444047505948:web:d8bfbfb666bb53ac8abdd9',
    messagingSenderId: '444047505948',
    projectId: 'workspace-292e5',
    authDomain: 'workspace-292e5.firebaseapp.com',
    storageBucket: 'workspace-292e5.firebasestorage.app',
    measurementId: 'G-TGB9FNJ9HR',
  );
}
